[project]
name = "simplestudio"
version = "1.0"
dependencies = [
    "customtkinter",
    "CTkMessagebox"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"



[tool.setuptools.package-dir]
"" = "src"

